name: adify
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  fluttertoast: ^8.2.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  google_sign_in: ^5.4.4
  oauth2: ^2.0.1
  crypto: ^3.0.2
  http: ^0.13.5
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  money_converter: ^2.0.2
  country_picker: ^2.0.20
  get_storage: ^2.1.1
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  razorpay_flutter: ^1.3.5
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
