class AppList{

 static const List<String> categoryList = [
  "Adventure sports theme parks",
  "Amusement and theme park",
  "Art Gallery and crafts",
  "Auditoriums",
  "Casinos",
  "Discotheques",
  "Event organisers",
  "Fashion show and beauty pageant organisers",
  "Fine art and canvas painting",
  "Fine arts and theatre",
  "Game show event organisers",
  "Go karting",
  "Hookah parlours",
  "Instrumental music classes",
  "Laser show organisers",
  "Light and sound services",
  "Lounges",
  "Magic show organisers",
  "Malls",
  "Mimicry show organisers",
  "Movie theatres",
  "Movie ticket booking",
  "Multiplex",
  "Museums",
  "Night clubs",
  "Playgrounds",
  "Projection equipment suppliers",
  "Pubs",
  "Race courses",
  "Radio stations",
  "Recreation clubs",
  "Resto bar",
  "Shopping places",
  "Social clubs and associations",
  "Stadiums indoor and outdoor",
  "Stage show organisers",
  "Summer swimming camps",
  "Swimming accessories shops",
  "Tourist places",
  "Trade fair organisers",
  "TV broadcasting services",
  "Vocal music classes",
  "Wedding organisers",
  "Zoos",
  "Auto rickshaw",
  "Automobile batteries",
  "Automobile glass dealers and services",
  "Automobile lubricants and oil dealers",
  "Automobile sticker shops",
  "Automotive accessories dealers",
  "Automotive engineers",
  "Bicycles",
  "Bike tyres",
  "Bikes resale",
  "Bus dealers",
  "Car dealers",
  "Car painting service",
  "Car service centres",
  "Car tyres",
  "Car wash",
  "Cars resale",
  "Commercial vehicle dealers",
  "Commercial vehicle repairs",
  "Driving schools",
  "E bike dealers",
  "Gas conversion kits dealers",
  "Heavy commercial vehicles",
  "Heavy commercial vehicles spares",
  "Heavy engineering equipment spares",
  "heavy engineering equipment",
  "Light commercial vehicles",
  "light commercial vehicle spares",
  "Mechanic and puncture shops",
  "Motorcycle accessories shops",
  "Motorcycle dealers",
  "Motorcycle service stations",
  "Motor cycle spare parts dealers",
  "Petrol pumps",
  "Pollution testing",
  "Tyres and wheels dealers",
  "Tyre retreaders",
  "Used car dealers",
  "AC spare parts dealers",
  "Acoustic home theatre system dealers",
  "Adhesive tape suppliers",
  "Agriculture machinery dealer",
  "Air compressor dealers",
  "Air curtain dealers",
  "Air filter suppliers",
  "Animation products and accessories dealers",
  "Asset Management software dealers",
  "Audio video equipment dealers",
  "Audio visual equipment dealers",
  "Ayurvedic medicine suppliers",
  "Bakery and confectionery machinery suppliers",
  "Barrel dealers",
  "Battery testing equipment dealers",
  "Beauty parlour products and equipment suppliers",
  "Billing machine dealers",
  "Biological specimen and equipment suppliers",
  "Building construction equipment dealers",
  "Bulldozer suppliers",
  "Burglar alarm system dealers",
  "Business card scanner dealers",
  "Canteen equipment dealers",
  "Cash register suppliers",
  "CCTV camera dealers",
  "Charcoal suppliers",
  "Chemical plant equipment suppliers",
  "Chocolate manufacturing machine suppliers",
  "CNC Router dealers",
  "Commercial kitchen equipment dealers",
  "Commercial refrigeration equipment suppliers",
  "Commercial refrigerator dealers",
  "Computer networking accessories dealers",
  "Conveyor system and equipment suppliers",
  "Cooling jacket suppliers",
  "Cooling machine dealers",
  "Corporate gift dealers",
  "Corrugated box suppliers",
  "Cotton and cotton products suppliers",
  "Currency machine dealers",
  "Digital display system dealers",
  "Disposable cutlery and utensils suppliers",
  "Domestic cleaning equipment suppliers",
  "Domestic pump suppliers",
  "Drinking water suppliers",
  "earthing electrode suppliers",
  "Electric Transformer dealers",
  "Electrical equipment and instrument dealers",
  "Elevator spare part dealers",
  "Fabric swatch card suppliers",
  "Fire alarm system dealers",
  "Fire fighting equipment dealers",
  "fork lift suppliers",
  "Frp products suppliers",
  "Garden umbrella suppliers",
  "Gas compressors parts suppliers",
  "Gas geyser dealers",
  "Gas water heater dealers",
  "Generator dealers",
  "Generator spare part dealers",
  "Generator dealers",
  "Hardware dealers",
  "home appliance spare part dealers",
 "House pipe suppliers",
 "Housekeeping equipment suppliers",
 "Hydraulic Equipment suppliers",
 "Ice cream machine dealers",
 "Industrial blower dealers",
 "Industrial chemical suppliers",
 "Industrial cleaning equipment dealers",
 "Industrial dust collector system dealers",
 "Industrial heater suppliers",
 "Industrial lubricant suppliers",
 "Industrial nuts and bolts suppliers",
 "Industrial pump suppliers",
 "Industrial refrigeration equipment suppliers",
 "Industrial safety shoes suppliers",
 "Industrial valves and cocks suppliers",
 "Industrial voltage stabilizers dealers",
 "Insulation material suppliers",
 "Kitchen cabinets and equipment suppliers",
 "Lab testing equipment dealers",
 "Labels and barcode sticker suppliers",
 "Lantern dealers",
 "Machinery tool and parts suppliers",
 "Magnet dealers",
 "Motor suppliers",
 "Name plate dealers",
 "Online UPS dealers",
 "Orthopaedic implant suppliers",
 "Ozonator dealers",
 "Packaging machinery dealers",
 "Packaging material suppliers",
 "Paint dealers",
 "Paper cup machine maker dealers",
 "Photocopier dealers",
 "Photography equipment dealers",
 "Plant and machinery dealers",
 "Plastic surgery product supplier",
 "Plastics and polymers suppliers",
 "Plumbing products suppliers",
 "Pneumatic system suppliers",
 "Point of sale equipment suppliers",
 "Popcorn making machine dealers",
 "Precision tools and instruments suppliers",
 "Printer dealers",
 "Printing dye suppliers",
 "Printing machinery suppliers",
 "Projector dealers",
 "Projector lamp supplier",
 "Road safety equipment dealer",
 "Robotic spares part dealer",
 "Safety door dealer scanner dealers",
 "school and college lab Equipment supplier",
 "Scientific Apparatus and instruments supplier",
 "Scrap dealers",
 "Scrap second hand item dealers",
 "Security system dealer",
 "Smart class equipment dealers",
 "Smoking accessories dealers",
 "Steel casting dealers",
 "Sun control film dealers",
 "Switchgear dealers",
 "Textile suppliers",
 "Transformer parts supplier",
 "Turnstile supplier",
 "UPS dealers",
 "Used photocopier dealer",
 "Valves and cock supplier",
 "Vending machine dealer",
 "Ventilation system dealers and rentals",
 "Water treatment equipment service and supplier",
 "Weight Bridge dealers",
 "Weighing scale dealers",
 "Weight and measure suppliers",
 "Weight loss equipment suppliers",
 "Wooden packaging box supplier",
 "White board dealers",
"",
 "Abortion clinics",
 "Acupuncture and acupressure doctors",
 "Anesthetics",
 "Andrologist",
 "Asthma and allergy",
 "Ayurvedic Clinic",
 "Beach flower Treatment Centre",
 "Bariatric surgeon",
 "Biomagnetic therapist",
 "Breast surgeons",
 "Cardiac surgeons",
 "Cardiologist",
 "Chest physicians",
 "Child Specialist",
 "Chiropractor",
 "Cosmetic surgeons",
 "Dental surgeons",
 "Dentists",
 "Diabetologist",
 "Dietitians",
 "Endocrinologist",
 "ENT specialist",
 "Fat reduction surgeons",
 "Foot surgeons",
 "Gastroenterologist",
 "General physicians",
 "General surgeons",
 "Gynecologist and obstetrician",
 "Hair transplant surgeon",
 "Hernia surgeons",
 "Homeopathy doctors",
 "Infertility treatment",
 "IUI Clinics",
 "IVF clinics",
 "Kidney stone treatment",
 "Laparoscopic surgeons",
 "Laser and Skin Clinics",
 "Lasik Surgeons",
 "Lipoma removal surgeons",
 "Natural cure treatment",
 "Naturopathy doctors",
 "Neurologist",
 "Neurotherapist",
 "Non surgical treatment",
 "Nursing homes",
 "nutritionist",
 "Obesity surgery",
 "Ophthalmologist",
 "Orthodontist",
 "Orthopaedic doctors",
 "Pathology and microbiology Labs",
 "Piles specialist",
 "Plastic surgeons",
 "Polyclinics",
 "Proctology and cryosurgery doctors",
 "Psoriasis treatment",
 "Psoriasis treatment clinics",
 "Psychiatrist",
 "Psychologist",
 "Radiologist",
 "Rheumatologist",
 "Sexologists",
 "Sexual Medicine Doctors",
 "Siddha doctor",
 "Silicone breast implant surgeons",
 "Silicone breast prosthetic suppliers",
 "Sinus doctors",
 "Small bowel resection surgeons",
 "Somnologist",
 "Sonologist",
 "Sperm Bank",
 "Spine and disk replacement surgeons",
 "Spleen removal surgeons",
 "Stomach cancer surgeons",
 "Surrogacy clinics",
 "Surrogate Motherhood centres",
 "Testicular surgeons",
 "Thyroid gland surgeons",
 "Tracheostamy surgeons",
 "Unani doctors",
 "Urologist and nephrologist",
 "Vagotomy surgeons",
 "Varicocele removal surgeons",
 "Vitiligo surgery",
 "Athletic wear shops",
 "Baby's clothing shops",
 "Boutiques",
 "Bridal wear designers",
 "Clothing rental shops",
 "Costume dealers",
 "Embroidery printing and design works",
 "Fashion designers",
 "Fitness apparel shops",
 "Footwear shops",
 "Handloom shops",
 "Jute and cotton bag dealers",
 "kids wear shops",
 "Leather stores",
 "Lingrie shops",
 "Luggage and accessories",
 "Maternity wear and accessory dealers",
 "Men and women clothing shops",
 "Men's clothing shops",
 "Men's readymade garment dealers",
 "Quilts and blanket dealers",
 "Saree wholesaler",
 "Shop repair and services",
 "Silk wholesalers and retailers",
 "Sportswear dealers",
 "Tailors",
 "Tie manufacturing",
 "Travel bag dealers",
 "Uniform fabric manufacturers",
 "Uniform suppliers",
 "Uniforms",
 "Used clothes dealers",
 "Women accessory shops",
 "Women's clothing shops",
 "Woolen wear clothing dealers",
 "10th standard tuition",
 "Accounts tuition",
 "Banks and insurance exam coaching",
 "Biochemistry tuition",
 "Botany classes",
 "CA CPT coaching",
 "CAT coaching",
 "CT entrance coaching",
 "CFA coaching",
 "Cfx coaching",
 "CMI coaching",
 "CMAT coaching",
 "Commerce tuition",
 "Competitive exam coaching",
 "Computer Science tuition",
 "CS coaching",
 "CTET Coaching",
 "Engineering tuition",
 "Entrance exam coaching",
 "Finance and accounting tuitions",
 "Government exam coaching",
 "GRE Coaching",
 "IBPS coaching",
 "ICWA coaching",
 "IELTS coaching",
 "JEE mains JEE advanced coaching",
 "KMAT coaching",
 "Language training",
 "Law entrance coaching",
 "Maths tuition",
 "MBBS tuition",
 "MCA entrance coaching",
 "Medical entrance coaching",
 "Microbiology tuition",
 "MPPSC entrance coaching",
 "NATA coaching",
 "Neet entrance coaching",
 "NTSE coaching",
 "Overseas MBA education Consultants",
 "Overseas medical education Consultants",
 "Overseas MS Consultants",
 "Physics classes",
 "PMT entrance coaching",
 "PTE coaching",
 "RRB coaching",
 "SAT coaching",
 "School tuitions",
 "School tuition 1st to 10th standard",
 "School tuition 6th to 10th standard",
 "SSC entrance coaching",
 "TANCET entrance coaching",
 "TOEFL coaching",
 "Tuition for 11th and 12th standard",
 "Adapting agencies",
 "Casket and coffins Dealers",
 "Cemeteries",
 "Community centres",
 "Cremation services",
 "De addiction and Rehabilitation centre",
 "Emergency services",
 "Funeral services",
 "Helplines",
 "Home for mentally retarded",
 "Nonprofit organisation",
 "Old age homes",
 "Orphanages",
 "Political organisations",
 "Post offices",
 "Ration card assistance",
 "Religious and spiritual centres",
 "Snake rescuer",
 "Social community Association",
 "Utilities",
 "Youth organisations",
 "AC design Consultants",
 "Acoustic Consultancy Services",
 "Building consultants and contractors",
 "Business consultancy",
 "Educational Consultants",
 "Engineering Consultant",
 "Farming Consultants",
 "GST Consultants",
 "HR Consultants",
 "Immigration Consultants",
 "Investment Consultants",
 "ISO Consultants",
 "It Consultants",
 "Labour legal service consultancy",
 "Management Consultants",
 "Market research consultant",
 "NGO consultant",
 "Overseas education Consultants",
 "Patent and Trademark Consultants",
 "Placement consultancies",
 "Project finance Consultants",
 "Project report thesis research papers Consulting Services",
 "Rainwater harvesting Consultants",
 "Real estate taxation consultancy",
 "Scholarship abroad Consultants",
 "Restaurant Consultant",
 "Social media Consultants",
 "Tax Consultants",
 "Vastu Consultants",
 "Visa Consultants",
 "AC dealers",
 "AC service and repair",
 "Air cooler dealers",
 "air purifier dealers",
 "Audio output dealers",
 "Audio system repairs",
 "Automatic water level controller",
 "Camera accessories",
 "Camera and video equipment dealers",
 "Camera repairs",
 "Chimneys",
 "Consumer electronics",
 "coocker and stove repairs",
 "Cooking range repairs",
 "Digital stores",
 "Dishwasher dealers",
 "DSLR products",
 "Electrical shops",
 "Elevator repairs",
 "Exhaust fan dealers",
 "Fans",
 "Furniture and sofa repairs",
 "Geyser and heater dealers",
 "geyser and heater repair",
 "Grinder repairs",
 "hob and Cook top repair",
 "Home products and services",
 "Home appliance rentals",
 "Home appliances repair and services",
 "Home Automation systems",
 "Home electronics and appliances dealers",
 "Home security system",
 "Induction stove dealers",
 "Inverters",
 "Kitchen electronics",
 "Lights and fixtures",
 "Microwave oven dealers",
 "Mixer grinder",
 "Photocopier dealers",
 "Refrigerator dealers",
 "Second hand home appliance dealers",
 "Solar heaters",
 "Solar panels installation and repair",
 "Solar product dealers and services",
 "TV dealers",
 "TV repairs",
 "Voltage stabilizers",
 "Washing machine dealers",
 "Water cooler dealers",
 "Wires and cables",
 "Water purifiers",
 "Ambulance and paramedic services",
 "Enquiry numbers",
 "Fire services",
 "Police stations",
 "Babysitters",
 "Camera repair and services",
 "bill payment centres",
 "Books",
 "Child care services",
 "Cook services",
 "Disinfection services",
 "Domestic help services",
 "Driver services",
 "Dry cleaners and laundry services",
 "Electricians",
 "Garbage cleaning services",
 "gardens gas agencies",
 "gas stove dealers",
 "Housekeeping services",
 "Key maker and locksmiths",
 "laundry machinery dealers repairs and rentals",
 "laundry services",
 "maid services",
 "marble cleaning services",
 "newspaper and magazine delivery service",
 "paper Products",
 "Pest control",
 "Pest control services",
 "Sealing machine services",
 "Stationery",
 "Tank water suppliers",
 "Tiffin services 3 star hotels",
 "5 star hotels",
 "Alcoholic beverage suppliers",
 "Bajji corners",
 "Bakeries",
 "Bars and restaurants",
 "Bewarage storage provider",
 "Biryani restaurant",
 "Budget hotels",
 "Cafe",
 "Cake shops",
 "Chinese restaurants",
 "Chocolates and ice cream parlours",
 "Copra dealers",
 "Dry fruit suppliers",
 "Edible oil dealer food Corner",
 "Food Product Suppliers",
 "Fruit and snack supplier",
 "Grocery store",
 "Goan cuisine restaurant",
 "gujarati cuisine restaurant",
 "Italian cuisine restaurant",
 "Kashmir equation restaurant korean restaurant",
 "Lebanese cuisine restaurant",
 "Mangalorean quizzard restaurant",
 "Meat and poultry shops",
 "milk and dairy products suppliers",
 "mughlai cuisine",
 "Night clubs and pubs",
 "Packet food service",
 "Restaurants",
 "Seafood stores",
 "Smoothies and milkshakes",
 "Mexican restaurant",
 "soft drink suppliers",
 "south Indian cuisine",
 "Spice shops",
 "sweet shops",
 "tea dealers",
 "tobacco shops",
 "thai restaurant",
 "Wine shops",
 "Death and birth registration office",
 "Employment offices",
 "Law and Justice officers",
 "Marriage registrar offices",
 "Passport Consultants",
 "Vehicle registration offices",
 "AIDS HIV centres",
 "Alternative Medicine suppliers",
 "Ambulance services",
 "Ayurvedic product dealers",
 "Bio magnetic therapy",
 "Birth centres",
 "Blood organ and tissue banks",
 "Cardiology hospitals cancer hospitals children's hospitals clinical Research and data management dermatologist diagnostic centres employee assistance program eye hospitals",
 "First aid kit",
 "Handicap AIDS and equipment suppliers",
 "Health equipments",
 "Health food and supplements",
 "Health Product Suppliers",
 "Hearing Aid supplier",
 "Hearing Aid repair and service",
 "Home Health Care",
 "Hypnotherapy",
 "IVF hospitals",
 "Kidney Care Centres",
 "Lens and optical shops",
 "Marriage counselling",
 "Maternity homes",
 "Medical counselling centre",
 "Medical equipment rentals",
 "Medical equipment repair and service",
 "Multispeciality Hospital",
 "Neurology hospitals",
 "Nutrition food suppliers",
 "Occupational therapy",
 "Orthopaedic hospitals",
 "Oxygen concentrator",
 "Pain management specialist",
 "Pharmacies",
 "Physiotherapy",
 "psychiatric hospitals",
 "Psychological counselling and healing services skin care and treatment",
 "Surgical equipment dealers tuberculosis Hospital agri products",
 "Bean bag dealers",
 "Crockery shops",
 "Cutting tools",
 "DIY home products",
 "Furniture rentals",
 "Furniture services",
 "Garden Product Suppliers",
 "Garden services",
 "Green Gate suppliers hardware shops",
 "Kitchenware product dealers",
 "Mirror sunglasses",
 "Outdoor decoration and furniture",
 "Photo framing works",
 "Plant nurseries",
 "Power tool dealer",
 "Radiator dealers",
 "Sealing machine dealers",
 "Steel utensils",
 "Water fountain",
 "Wall decor",
 "Water fountain dealers",
 "Bending and metal work machines",
 "casting and moulding equipments",
 "Drilling and boring equipments",
 "Industrial clothing",
 "Industrial parts",
 "Industrial hardwares industrial tools",
 "Instrumentation and control equipments",
 "Milling and grinding tools",
 "Safety comments testing and measuring recruitments welding equipments and machines",
 "Welding services",
 "Aadhar Card agents",
 "Accident insurance",
 "Advocate and lawyers",
 "Arbitration services",
 "Angel investor",
 "ATMs",
 "Auditor's",
 "Bank drop boxes",
 "Banks",
 "Business loans",
 "CA services",
 "Company registration",
 "co-op society billing and accounting",
 "Construction loans",
 "Criminal lawyers",
 "Corporate lawyers",
 "Court marriage lawyers",
 "Credit card providers",
 "digital signature",
 "Divorce lawyers education loans",
 "Equity firm",
 "ESI and PF",
 "Finance and taxation services",
 "Fire insurance",
 "Foreign exchange and money transfer service",
 "Four wheeler insurance",
 "Four wheeler loans",
 "Fssai licence",
 "Gold loans",
 "High court lawyers",
 "Home Insurance",
 "Home loans",
 "Industrial labour lawyers",
 "Legal document writers",
 "Insurance",
 "Insurance on accidental claim lawyers",
 "Lawyer",
 "Legal document writers",
 "Life Insurance medical insurance",
 "Mortgage Loan",
 "Notary",
 "Pawnbrokers",
 "Payroll services",
 "Personal loans",
 "Plot loans",
 "Project insurance",
 "Property lawyers",
 "Real estate appraisal",
 "Safe deposit locker facility",
 "SSO registration",
 "Tax return filing",
 "Trade licence",
 "Travel insurance",
 "Two wheeler loans",
 "USA tax filing service",
 "Venture capitalist",
 "Wealth Management",
 "Agarbatti manufacturers",
 "Bandra",
 "Barbeque dealer",
 "binding machine manufacturers",
 "Boiler manufacturer",
 "scissor lift manufacturer",
 "Cable manufacturer",
 "Chemical manufacturer and dealer",
 "Control panel accessories manufacturer",
 "Control panel board and cabinet manufacturer",
 "Crane manufacturer",
 "Electrical equipment and instrument manufacturers",
 "Electronic weighing scale manufacturer",
 "Elevator manufacturer",
 "Manufacturer",
 "Fabrication manufacturer",
 "Gym equipment manufacturer",
 "Gift box manufacturer",
 "Hologram manufacturer",
 "Ice manufacturer",
 "Industrial chiller manufacturers",
 "Industrial cooling tower and water plant manufacturer",
 "Industrial water cooler manufacturers",
 "Jacket manufacturers",
 "Jewellery box manufacturers",
 "Lamination machine manufacturer",
 "LED display light manufacturer",
 "Mineral water manufacturer",
 "Packaging machinery and parts manufacturer",
 "Paper roll manufacturer",
 "Paper shredder and paper cutter manufacturer",
 "PCB manufacturer",
 "Pharmaceutical manufacturer and wholesaler",
 "Pipe manufacturers",
 "plastic ID card machine manufacturer",
 "Pool manufacturers",
 "Rubber product manufacturers and suppliers",
 "Sign making machine manufacturer",
 "Slotted angles manufacturers",
 "Vehicle body manufacturers",
 "Water purification plant manufacturers",
 "Weighing scale manufacturers",
 "Wooden pallet manufacturers and dealers",
 "Artificial flower shops",
 "Artist on hire",
 "Astrologers",
 "Bridal shops",
 "Catering services",
 "Chocolate gift pack suppliers",
 "Christmas decoration",
 "Convention centre",
 "Costume rentals",
 "Dance props",
 "Event decorators",
 "Event equipment rentals",
 "fire cracker supplier",
 "florist",
 "Horse for hire",
 "Ice cream supplier",
 "Marriage halls rentals",
 "Matrimonial services",
 "Mehandi design service",
 "Outdoor cooling system supplier",
 "Party and banquet hall rentals",
 "Party lawns and farm",
 "photo booth rentals",
 "Photographers and videographers",
 "Priest and Purohit",
 "Register offices",
 "Shamiana rentals",
 "tent supplier",
 "Wedding card and invitations of",
 "Wedding party comment supplies",
 "Agar",
 "Acting classes",
 "Aerobic centres",
 "Aromatherapy centre",
 "Art and craft classes",
 "Ayurvedic Shop",
 "Bath and body products",
 "Beauty parlour services",
 "Bollywood dance classes",
 "Bridal makeup",
 "Classical dance",
 "Dance classes",
 "filmmaking schools",
 "Fitness classes",
 "Fitness equipment repair and service",
 "Fitness equipment service",
 "Fitness product dealers",
 "Gyms",
 "Hair Care treatment",
 "Health clubs",
 "Herbal product dealer",
 "Hip hop dance Plus",
 "Hobby classes",
 "Horse riding Academy",
 "Instrument music class",
 "Language classes",
 "Makeup and hairstyle",
 "Massage centres",
 "Massage Equipment supplier",
 "Meditation and relaxation",
 "Meditation centres",
 "Modelling schools",
 "Naturopathy centre",
 "Painting classes",
 "Perfume shops",
 "Personal care product",
 "Personal fitness trainer",
 "Photography classes",
 "Pilate studios",
 "Reformer studios",
 "Salon",
 "Salsa dance classes",
 "Spa centre",
 "Tattoo and body piercing",
 "Vegan products",
 "Walking stick dealers",
 "Weight loss centre",
 "weight reduction",
 "Western music classes",
 "Wings and weaving shops",
 "Yoga centres",
 "Zumba classes",
 "Aquarium suppliers",
 "Aquarium service",
 "pet accessories",
 "Pet care services",
 "Pet food",
 "Pet shop",
 "Veterinary hospitals",
 "Veterinary machine manufacture",
 "3D interior designers",
 "Accommodation brokers",
 "Aluminium Fabricators",
 "Apartment promoters",
 "Architects",
 "Bathroom accessories and sanitary ware dealers",
 "Bathroom interior designer",
 "Bathroom interior design",
 "Bedroom interior design",
 "Bison panel suppliers",
 "Bore well contractor",
 "Builders and promoters",
 "Building contractors",
 "Building machinery rentals",
 "Building Maintenance Services",
 "Building plan sanction",
 "Carpentry contractors",
 "Civil contractors",
 "Commercial Architects",
 "Construction contractors",
 "construction machinery dealer and manufacturers",
 "Contract engineers",
 "Contactors",
 "Doors and window dealers",
 "Drainage contractor",
 "Drilling contractors",
 "Electrical contractor",
 "Elevator contractors",
 "enclosure and partition dealers",
 "Exterior painting contractors",
 "False ceiling contractor",
 "Farmhouse",
 "Fencing contractor",
 "Fixture and fitting dealer",
 "Flooring contractor",
 "Garden contractor",
 "Home automation system dealer",
 "Home interior designers",
 "Home painting services",
 "House rentals",
 "Industrial design services",
 "Industrial flooring contractor",
 "Interior painting contractor",
 "Kids hostels",
 "Kitchen interior design",
 "Labour contractor",
 "Land surveyors",
 "Living room interior design",
 "Marbles and Granites",
 "Lodging",
 "Mens hostel",
 "Modular kitchen",
 "Office interior designers",
 "Office lease and rental",
 "Painting contractor",
 "Painting works",
 "Paying guest",
 "Pipeline contractor",
 "Portable cabin",
 "Portable cabins dealer",
 "Precast compound wall",
 "Prefabricated building service",
 "Promoters and developers",
 "Property dealers",
 "Property brokers",
 "Property Management Service",
 "PVC modular kitchen",
 "Real estate",
 "Real estate appraisers",
 "Real estate agents",
 "Real estate developers",
 "Real estate joint venture",
 "Rental agency",
 "Rentals",
 "Residential Architects",
 "Resort booking office",
 "Resort",
 "Road construction contractor",
 "Scaffolding manufacturer",
 "Shop interior design",
 "Showroom interior design",
 "Solar product dealer",
 "Staircase manufacturer",
 "Swimming pool contractor",
 "Tensile membrane structure manufacturer",
 "Tiles and ceramics",
 "Tiling contractor",
 "Urban designer architect",
 "waterproofing contractor",
 "Welding contractor",
 "Welding service",
 "Womens hostel",
 "Youth Hostels",
 "Antique dealers",
 "Babies product shops",
 "Bed sheets blankets curtains",
 "Carpet and rugs",
 "Dairy product",
 "Cosmetics",
 "Fancy store",
 "Fresh fruit Mart",
 "Games Android stores",
 "Gems and Diamonds",
 "gift shops",
 "Gemstone dealer",
 "Gift shops",
 "Gold Jewellers",
 "Goldsmith",
 "Groceries",
 "Handicraft",
 "Imitation jewellery dealer",
 "Jewellery shops",
 "Kirana store",
 "Malls and shopping centres",
 "Mattress cushion and pillows",
 "Musical instruments",
 "Natural and Organic products shops",
 "Organic fruit and vegetable Store",
 "Plastic cover wraps and bags",
 "Plastics for homes",
 "Religious store",
 "Silver Jewellers",
 "Sunglasses",
 "Supermarket",
 "Telescope and Binocular dealer",
 "Vegetables",
 "Watches and sunglasses",
 "Watches dealers and services",
 "White metal gift shop",
 "Agriculture College",
 "Anglo Indian School",
 "Art and craft supplier",
 "Arts and Science College",
 "Aviation college",
 "Ayurvedic College",
 "BA Distance education",
 "BCA distance education",
 "BCom distance education",
 "B e college",
 "B.Ed distance education",
 "BBA distance education",
 "Binding and photocopy shop",
 "Book banks",
 "Book shop",
 "Business College",
 "Colleges and Universities",
 "Dental College",
 "Distance education",
 "Educationrecruitment dealer",
 "Educational supplies",
 "Engineering College",
 "Homeopathy college",
 "ICSE schools",
 "Hotel Management College",
 "International Schools",
 "Law College",
 "Libraries",
 "LLB distance education",
 "MBA college",
 "MBA distance education",
 "M com distance education",
 "M Tech distance education",
 "Madrasa School",
 "MBBS college",
 "Media and Mass Communication college",
 "Medical College",
 "Montessori School",
 "MSc IT distance education",
 "Naturopathy and yogic Science College",
 "Nursing college",
 "Ophthalmology college",
 "PhD distance education",
 "Pharmacy College",
 "Physiotherapy College",
 "Playgroup equipment",
 "Play School",
 "Polytechnic College",
 "PU College",
 "Residential School",
 "School project kit supplier",
 "School retakers",
 "Schools",
 "Stationery shops",
 "universities",
 "Veterinary College",
 "Vocational College",
 "Women's College'3D laser scanning service",
 "Actuarial service",
 "Advertising agency",
 "Air compressor rental",
 "Air compressor repair service",
 "Air compressors",
 "Art carving service",
 "Auctioneer",
 "Audio visual equipment rental",
 "Audio visual system repair and service",
 "Battery rental",
 "Battery repair and service",
 "Blinds installation service",
 "Building construction equipment rental",
 "Business centres",
 "Business database provider",
 "CAD Engineering Service",
 "Call Centre solution provider",
 "Call Centre dialler solution provider",
 "Campus recruitment training",
 "Cargo and shipping agents",
 "Certificate agents",
 "Chemical water treatment service",
 "Chiller repair and service",
 "Cleaning services",
 "Cold storage manufacturers and service",
 "Company secretary service",
 "Computer networking service",
 "Content writers",
 "Corporate gifts printing",
 "Corporate internet service provider",
 "Corporate training provider",
 "Cost accountant",
 "Courier service",
 "Crane rental",
 "Crane service",
 "Currency counting machine repair service",
 "Data centre and Co location service",
 "Deep freezer rental",
 "Designing graphic service",
 "Desktop publisher",
 "Detailed project report service",
 "Detective agencies",
 "Document Management Services",
 "Email solutions",
 "Embedded system service",
 "Engineering supplies",
 "Environment pollution control",
 "Event organisers",
 "Exhibition stall designer",
 "Fabrication engineer",
 "Farm management solution",
 "Fax machine dealers and service and rentals",
 "Ferrous and non ferrous casting service",
 "Fire fighting equipment AMC service",
 "Fire fighting equipment repair and service",
 "Fruit vegetable and nuts processing machine",
 "Fumigation service",
 "Generator rentals",
 "Generator repair service",
 "Guest house",
 "geo technical service",
 "Guest house",
 "Hydraulic Equipment service",
 "Industrial Automation system provider",
 "Industrial chains wholesaler",
 "Industrial dry cleaners and laundry service",
 "Industrial Electrical system service",
 "Industrial electronics",
 "Industrial pump rental",
 "Repairing Service",
 "Industrial agent recruiter",
 "Insurance agent recruiter",
 "Interactive virtual video service",
 "Interactive voice response provider",
 "Inverter dealer and services and rentals",
 "Inverter repair",
 "Iron and steel Merchant",
 "It system integrator",
 "Jewellery design",
 "Jewellery valuers",
 "Laser cutting service",
 "Liaisoning service",
 "Wireless Wi-Fi service",
 "Meat seafood and poultry processing machine",
 "Medical translation service",
 "Metal cleaning service",
 "metal surface coating",
 "Mud pump drilling fluid service",
 "Online lottery agency",
 "Online chat service",
 "Paint shop",
 "Parking contractor",
 "Pesticide retailer",
 "Pharma and surgical distributors",
 "Photocopier rental",
 "Photocopier services",
 "Pipeline works",
 "Poultry farm",
 "Powder coating services",
 "Power sector products and system dealers",
 "Predictive dialler solution provider",
 "Press media and Publication service",
 "Printing machine repair and service",
 "Printing services",
 "Product design services",
 "Production house",
 "Projector rental",
 "Projector services",
 "Psychometric testing centre",
 "Public relation agencies",
 "Radiator service",
 "Safety comment service",
 "Satellite internet provider",
 "Scanner repair and services",
 "Scrap buyers",
 "Screen projection manufacturers",
 "Security System rentals",
 "Sign board agencies",
 "software development services",
 "Software companies",
 "Soil testing lab",
 "Stone cleaning service",
 "storage Facility provider",
 "Toll free number provider",
 "Towing and recovery services",
 "Translators and interpreters",
 "Typewriter machine dealers and service and rentals",
 "UPS rental",
 "UPS service",
 "Vending machine rental",
 "Vending Machine repair and service",
 "Water purification service",
 "Water purifier services",
 "Water Tank repair and maintenance service",
 "Web design and development",
 "Weighbridge service",
 "2D animation training",
 "3D modelling training",
 "3D Movie Maker training",
 "4D animation training",
 "Accounting job training",
 "Adobe Illustrator training",
 "Adobe indesign training",
 "Adobe Photoshop training",
 "AutoCad training",
 "Autodesk Revit mep designing",
 "Aviation management training",
 "BPO Services",
 "Call centre and BPO training",
 "Catia training",
 "Civil CAD training",
 "Clinical Research training",
 "Cloud Computing training",
 "Communication skills training",
 "Comptia training",
 "Construction safety training",
 "CorelDRAW training",
 "Cswip training",
 "Cyber security training",
 "Data science and business analytics training",
 "Database training",
 "Del cam training",
 "Designing tools training",
 "Digital marketing training",
 "Electrical engineering job training",
 "Electronic security training",
 "Enterprise software training",
 "Fashion designing training",
 "Finance training",
 "Financial risk management training",
 "First aid training",
 "Fitness training",
 "Graphic design training",
 "Hospital management training",
 "HVAC job training",
 "Industrial safety training",
 "It administrator and architecture training",
 "IT hardware and networking training",
 "It programming language training",
 "IT project training",
 "IT services",
 "JavaScript online training",
 "jsp online training",
 "Leadership management training",
 "Learning disability training",
 "MEP training",
 "Mobile app development training",
 "Montessori teacher training",
 "NDT training",
 "NEBOSH training",
 "Oracle training",
 "Orcad training",
 "Personality development training",
 "PHP online training",
 "Pilot training",
 "PLC training",
 "Project management certification training",
  "Quality management training",
  "Radio jockey training",
  "Retail banking training",
  "SAP Training",
  "Scada training",
  "Security guard training",
  "SEO training",
  "Shorthand training",
  "Soft skills training",
  "Software engineering training",
  "Software services",
  "SPM training",
  "Spring online training",
  "Stress management training",
  "Tailoring classes",
  "Taxation training",
  "Teacher training",
  "Telecom and datacom training",
  "Telecom training",
  "Type writing training",
  "VB.net online training",
  "VB script online training",
  "VFX multimedia training",
  "VFX training",
  "Web design services",
  "Web designer online training",
  "Web development services",
  "Web hosting services",
  "Web technologies online training",
  "Web technologies training",
  "Website services",
  "Athletics",
  "Badminton",
  "Basketball",
  "Snooker",
  "Billiard and pool",
  "Bowling Games",
  "Boxing",
  "Boxing games",
  "Chess",
  "cricket ground",
  "Cycling",
  "Football",
  "Golf",
  "Gymnastic",
  "Hiking and camping",
  "Hockey",
  "Judo",
  "Karate",
  "Karate class",
  "Physical training academy",
  "Play stations",
  "Roller skating games",
  "Skating",
  "Self defence training",
  "Sports coaching",
  "Sports goods and accessories dealers",
  "Sports infrastructure",
  "Sports psychology coaching",
  "Squash",
  "Swimming",
  "Tennis",
  "Table tennis",
  "Video game station",
  "Volleyball",
  "Water games",
  "ACT Broadband",
  "Airtel broadband",
  "Apple service centre",
  "Apple Store",
  "Asus laptop service centre",
  "Broadband service",
  "Cameras",
  "Ink dealers",
  "Computer AMC service",
  "Computer motherboard repair",
  "computer printer repair",
  "Computer scanners repair",
  "Dell laptop service centre",
  "Digital accessories",
  "Digital accessory service centre",
  "DTH provider",
  "Electronic equipment",
  "Hathway Broadband",
  "HP laptop service centre",
  "Intercom system connection provider",
  "Internet service provider",
  "Jio Store",
  "Laptop charger repair",
  "Laptop service centre",
  "Laptops resale",
  "Laptop showroom",
  "Lenovo laptop service centre",
  "Make a Linux server backup",
  "MI service centre",
  "Mobile accessories",
  "Mobile resale",
  "Mobile service centre",
  "Music system dealer",
  "My Airtel store",
  "Network cabling services",
  "Oneplus service centre",
  "Oneplus showroom",
  "Oppo service centre",
  "Oppo showroom",
  "Realme service centre",
  "Realme showroom",
  "Reliance broadband",
  "Satellite TV dealers",
  "Set top box",
  "Sim stores",
  "TV cable providers",
  "VI stores",
  "VPN services",
  "Vivo service centre",
  "Vivo showroom",
  "VR equipment",
  "Wireless communication system",
  "Wireless walkie tockie dealer and service",
 "Two wheeler rentals",
 "Adventure sports",
 "Adventure trips",
 "Air charter service",
 "Air travel agent",
 "Airlines",
 "Airport",
 "All courier service",
 "Bike rentals",
 "Blue Dart",
 "Bus rental",
 "Bus travel agent",
 "Car rentals",
 "Consulates and embassy",
 "Cottages",
 "Custom clearance",
 "D h i",
 "Domestic air cargo",
 "Domestic courier service",
 "Domestic Packers and Movers",
 "Domestic Railway cargo",
 "DTDC",
 "FedEx",
 "First Flight",
 "Goods and careers",
 "Hotel reservation agents",
 "Hotels",
 "industrial Packers and Movers",
 "International sea cargo",
 "Packed food service",
 "Packers and Movers",
 "Parcel booking service",
 "Passport agent",
 "Petroleum Transporters",
 "Pick up drop off",
 "Professional Couriers",
 "Service apartment",
 "Shipping",
 "Speed post",
 "Tempo rental",
 "Tour operator",
 "Tourism department offices",
 "Tours and travels",
 "Trackon",
 "Trailer Transporters",
 "Train travel agents",
 "Transporters",
 "Travel agents",
 "Trekking",
 "Water sports",
 "Vichare",
  ];
 }